#!/bin/sh

#
# get the mockup bin in our path that fakes out condor_q
export PATH="$POMS_DIR/test/bin_mock1:$PATH"

#
# start the fake webservice on port 8888
python $POMS_DIR/test/fake_webservice/fake_webserver.py 2> web_out1 &
wspid=$!

#
# have jobsub_q scraper run one pass with the faked-out condor_q
# with each sample output
for OUTPUT in `cd $POMS_DIR/test/data; echo condor*`
do
   export OUTPUT
   python $POMS_DIR/job_broker/jobsub_q_scraper.py -t 
done

sleep 1
kill $wspid
