#!/bin/sh

campaign_id=
launcher=

while :
do
case x$1 in
x--campaign_id=*) campaign_id=`echo $1 | sed -e 's/.*=//'`; shift;;
x--launcher=*) launcher= `echo $1 | sed -e 's/.*=//'`; shift;;
*) break;;
esac
done

ds=`date +%Y%m%d_%H%M%S`
outdir="$HOME/private/logs/poms/launches/campaign_$campaign_id"
outfile="$outdir/$ds"
mkdir -p $outdir
url="http://127.0.0.1:8080/poms/launch_jobs?campaign_id=$campaign_id"

wget --tries=1 --timeout=0 -o outfile.log -O /dev/null "$url"
